### PR TITLE
playback: fix error 404 when seeking before start of segment (#4276) (#4533)

### LINKED ISSUE #4276: No recording segments found asking near a segment start time inside a timespan returned by the
### Which version are you using?

1.10.0

### Which operating system are you using?

Linux amd64 Docker

### Describe how to replicate the issue

When making an HTTP request to the playback server to list the available recordings from a stream, I get a single timespan starting at a given time that has a duration of well over an hour, as you can see in the following image:

Image

We then try to make a GET request to the playback server to get a video, using a start query parameter that is just milliseconds earlier than one of the recording segments found on the recordings folder where they are stored:

Image

As you can observe, the timestamp is inside the timespan returned by the list HTTP request. When we try to make the GET request we get the message "no recording segments found":

Image

As you can see, the start query parameter timestamp has a value of 676 milliseconds, and the timestamp found on the recording file name is 687. 

If we increase or decrease the start timestamp requested, then we are able to download the video without any problem, using milliseconds values of 587 or 787.

### Server logs

_No response_

### Network dump

_No response_

### PR DESCRIPTION
**Pull request by aler9**
Fixes #4276
Replaces #4533

### CODE REVIEW

**Comment by tvidaldev** [comment]
I can confirm the PR fixes the issue.
Waiting now for the linter issue, anyway I can use the branch fix/playback-between until merged.
Thanks @aler9!

File: internal/playback/segment_fmp4.go [hunk 1]
```diff
@@ -490,10 +484,6 @@ func segmentFMP4SeekAndMuxParts(
 		return 0, err
 	}
 
-	if !atLeastOnePartWritten {
```
Comment (IDisposable) [inline internal/playback/segment_fmp4.go:493]: This duplicate code warning is not _exactly_ true... these two `func` are now **almost** identical, except for one line 

In `segmentFMP4SeekAndMuxParts` [line 427](https://github.com/bluenviron/mediamtx/pull/4539/files#diff-17995db508ad7dc9d924e5aff2204e8376fcd5b8c6160eccc191fb25ed1b0fceR427) reads
```go
muxerDTS := int64(tfdt.BaseMediaDecodeTimeV1) - segmentStartOffsetMP4
```

In `segmentFMP4MuxParts` [line 547](https://github.com/bluenviron/mediamtx/pull/4539/files#diff-17995db508ad7dc9d924e5aff2204e8376fcd5b8c6160eccc191fb25ed1b0fceR547) reads
```go
muxerDTS := int64(tfdt.BaseMediaDecodeTimeV1) + segmentStartOffsetMP4
```

I assume that one of these two is incorrect because the first one `-` subtracts the `segmentStartOffsetMP4` while the second one `+` adds the `segmentStartOffsetMP4`.  

I am not sure that's an intentional difference.

If not intentionally different, I am not sure which one is **correct** (I suspect the `+` addition is right... but I have no idea).  After anointing the correct version, all calls to the other can be swapped and the (now entirely) duplicate can be deleted. In other words, pick if it's supposed to be `+` or `-` and replace all calls to `segmentFMP4MuxParts` with a call to `segmentFMP4SeekAndMuxParts`, then delete the entire  `segmentFMP4MuxParts`  duplicate.

If the difference is intended, would it be smart to have that single line conditional on a flag and have a helper `func` that does the work, being called from these two stub functions . In other words, make the body `segmentFMP4SeekAndMuxParts` call `implSegmentFMP4SeekAndMuxParts` passing along all the arguments and a `true` and have  `segmentFMP4MuxParts` call `implSegmentFMP4SeekAndMuxParts` passing along all the arguments and a `false`, then in that helper `implSegmentFMP4SeekAndMuxParts` have the [_effective_ line 427](https://github.com/bluenviron/mediamtx/pull/4539/files#diff-17995db508ad7dc9d924e5aff2204e8376fcd5b8c6160eccc191fb25ed1b0fceR427) read something like this (comment syntax check, sorry)

```go
if (flag) {
   muxerDTS := int64(tfdt.BaseMediaDecodeTimeV1) - segmentStartOffsetMP4
} else {
   muxerDTS := int64(tfdt.BaseMediaDecodeTimeV1) + segmentStartOffsetMP4
}
```

Comment (IDisposable) [reply internal/playback/segment_fmp4.go:493]: @aler9 I'm still concerned about the potential typo commented ☝️

Comment (aler9) [reply internal/playback/segment_fmp4.go:493]: @IDisposable thanks for the report, I noticed the plus/minus sign issue and some other things and that's the reason why this PR is temporarily paused.

**Review by IDisposable — APPROVED** [review]
Much cleaner
